sudo: required
dist: trusty
language: go

install:
  - sudo apt-get install capnproto
  - go get -u github.com/jteeuwen/go-bindata/...
  - sudo add-apt-repository --yes ppa:fkrull/deadsnakes 
  - sudo apt-get update
  - sudo apt-get install --force-yes python3.5 python3.5-dev
  - wget -q -O - https://bootstrap.pypa.io/get-pip.py | sudo python3.5 
  - sudo pip3 install autopep8
go:
  - 1.8
  - 1.9

script:
  - ./build_apidocs.sh
  - make install
  - make test
  - cd codegen/python/gentest && sudo pip3 install -r requirements.txt && nose2
