sudo: required
dist: trusty
language: go

install:
  - sudo apt-get install capnproto
  - go get -u github.com/jteeuwen/go-bindata/...

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9

script:
  - make apidocs
  - make install
  - make test
